<?php

use Illuminate\Database\Seeder;

class product extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

    	$product = [
    		[
    			'name' => 'Quần culotte xếp ly trước cơ bản ',
    			'image' => '',
    			'price' => 5,
    			'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
    			'amount' => 1,
    			'discount' => 0,
    			'hot' => true,
    			'gender_id' => 2,
    			'product_category_id' => 2,
    		],
    		[
    			'name' => 'Đầm bút chì sát nách nhấn dây lưng',
    			'image' => '',
    			'price' => 8,
    			'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
    			'amount' => 3,
    			'discount' => 10,
    			'hot' => false,
    			'gender_id' => 2,
    			'product_category_id' => 2,
    		],
    		[
    			'name' => 'Đầm tay phồng hạ eo hoạ tiết dập nổi',
    			'image' => '',
    			'price' => 15,
    			'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
    			'amount' => 20,
    			'discount' => 5,
    			'hot' => false,
    			'gender_id' => 2,
    			'product_category_id' => 2,
    		],
    		[
    			'name' => 'Đầm 2 dây nơ ngực hoạ tiết dập nổi',
    			'image' => '',
    			'price' => 10,
    			'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
    			'amount' => 5,
    			'discount' => 0,
    			'hot' => true,
    			'gender_id' => 2,
    			'product_category_id' => 2,
    		],
    		[
    			'name' => 'Áo len form ôm cơ bản',
    			'image' => '',
    			'price' => 5,
    			'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
    			'amount' => 1,
    			'discount' => 0,
    			'hot' => false,
    			'gender_id' => 2,
    			'product_category_id' => 1,
    		],
    		[
    			'name' => 'Áo thun trễ vai nhấn nút',
    			'image' => '',
    			'price' => 8,
    			'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
    			'amount' => 3,
    			'discount' => 10,
    			'hot' => true,
    			'gender_id' => 2,
    			'product_category_id' => 1,
    		],
    		[
    			'name' => 'Váy mini xếp ly nhấn nút gold',
    			'image' => '',
    			'price' => 15,
    			'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
    			'amount' => 20,
    			'discount' => 5,
    			'hot' => false,
    			'gender_id' => 2,
    			'product_category_id' => 2,
    		],
    		[
    			'name' => 'Áo sơ mi cổ trụ tay dài hoạ tiết hoa',
    			'image' => '',
    			'price' => 50,
    			'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
    			'amount' => 5,
    			'discount' => 0,
    			'hot' => true,
    			'gender_id' => 2,
    			'product_category_id' => 1,
    		],
    		[
    			'name' => 'Áo khoác jean nam form Loose',
    			'image' => '',
    			'price' => 5,
    			'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
    			'amount' => 1,
    			'discount' => 0,
    			'hot' => true,
    			'gender_id' => 1,
    			'product_category_id' => 1,
    		],
    		[
    			'name' => 'Áo sơ mi nam tay dài cổ thường form fitted',
    			'image' => '',
    			'price' => 8,
    			'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
    			'amount' => 3,
    			'discount' => 10,
    			'hot' => false,
    			'gender_id' => 1,
    			'product_category_id' => 1,
    		],
    		[
    			'name' => 'Áo sơ mi nam tay dài, kẻ sọc form Fitted',
    			'image' => '',
    			'price' => 15,
    			'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
    			'amount' => 20,
    			'discount' => 5,
    			'hot' => true,
    			'gender_id' => 1,
    			'product_category_id' => 1,
    		],
    		[
    			'name' => 'Áo thun nam tay ngắn xẻ lai form LOOSE',
    			'image' => '',
    			'price' => 50,
    			'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
    			'amount' => 5,
    			'discount' => 0,
    			'hot' => true,
    			'gender_id' => 1,
    			'product_category_id' => 1,
    		],
            [
                'name' => 'Quần Jean rách nam dây kéo lai form SKINNY CROP',
                'image' => '',
                'price' => 24,
                'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
                'amount' => 5,
                'discount' => 0,
                'hot' => true,
                'gender_id' => 1,
                'product_category_id' => 2,
            ],
            [
                'name' => 'Quần jean nam trơn form slim',
                'image' => '',
                'price' => 80,
                'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
                'amount' => 5,
                'discount' => 0,
                'hot' => false,
                'gender_id' => 1,
                'product_category_id' => 2,
            ],
            [
                'name' => 'Quần vải nam lưng thun Deco sau form Straight Crop',
                'image' => '',
                'price' => 40,
                'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
                'amount' => 5,
                'discount' => 0,
                'hot' => false,
                'gender_id' => 1,
                'product_category_id' => 2,
            ],
            [
                'name' => 'Quần short nam form Slimfit',
                'image' => '',
                'price' => 10,
                'description' => 'Hàng nhập khẩu, chất lượng cao, giá rẻ, uy tín số 1',
                'amount' => 5,
                'discount' => 0,
                'hot' => true,
                'gender_id' => 1,
                'product_category_id' => 2,
            ],
    	];

        \DB::table('product')->insert($product);
    }
}
